---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: Copy the code from repository
  git:
    repo: https://github.com/bennojoy/mywebapp.git
    dest: /var/www/html/

- name: Creates the index.php file
  template:
    src: index.php.j2
    dest: /var/www/html/index.php
